file = open("day12.txt","w+")
print("File is created and the data is written as : ")
file.write("30 days 30 hour challenge")
file.close()
file = open("day12.txt","r")
print(file.read())
file.close()
file = open("day12.txt","a")
file.write("\nName : Bernice")
file.close()
file = open("day12.txt","r")
print("after append operation :")
print(file.read())
file.close()

